### ISSUE TITLE
[RFC] remove the difference between resources and late resources

### ISSUE THREAD

**Issue by TeXitoi** [rtfm-rs/rfcs#15]
# Summary

Resources and late resources are distinct in RTFM, when it's not really needed. static definition with SHOUTING_NAMES are also a bit strange when accessed by the `resources` magic parameter.

This RFC proposes a new syntax for declaring resources that remove the distinction between resources and late resources, and feel a bit more rustic.

# Background

Consider this example:

```rust
#[rtfm::app(device = ..)]
const APP: () = {
    // Strange syntax of late resource
    static mut FOO: ComplexThing = ();

    // As resources are presented as statics, they are in SHOUTING_SNAKE_CASE
    static mut BAR: i32 = 42;

    // `init::LateResource` is a magic type
    #[init]
    fn init() -> init::LateResources {
        init::LateResources {
            // strange SHOUTING_FIELD
            FOO: make_foo(),
        }
    }

    #[task(priority = 1, resources = [FOO, BAR])]
    fn foo() {
        // strange SHOUTING_FIELDS
        resources.BAR = resources.FOO.get_bar();
    }
};
```

# Design

The main idea is to declare a struct representing the resources. This struct is returned by init. Then, you have a partial view of this struct in the handlers.

```rust
#[rtfm::app(device = ..)]
const APP: () = {
    // define the resources by defining a struct
    #[resources]
    struct Resources {
        // as this is fields of a struct, we don't use shouting case here
        foo: ComplexThing,
        bar: i32,
    }

    // just return the declared Resources struct
    #[init]
    fn init() -> Resources {
        Resources {
            foo: make_foo(),
            // no more static initialization
            bar: 42,
        }
    }

    // declare the fieds of our `resources` variable as a subset of the Resource fields
    #[task(priority = 1, resources = { foo, bar })]
    fn foo() {
        // natural naming
        resources.bar = resources.foo.get_bar();
    }
};
```

# Drawbacks

`init` is no longer optional (when there is resources), thus complicating the simple case a bit.

As the `init` function returns all the resources, there is no more static initialisation of the static resources, potentially adding useless memcpy.

**Comment by japaric** [comment]
this was superseded by rtfm-rs/cortex-m-rtfm#212
